"""add_task_completed_to_project_agents

Revision ID: 7f25ed6f8042
Revises: 5627115ed9ab
Create Date: 2026-04-15 06:59:19.496772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f25ed6f8042'
down_revision: Union[str, None] = '5627115ed9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_agents', sa.Column('task_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_agents', 'task_completed')
    # ### end Alembic commands ###
